site_name: Aplicatie - Bibilioteca
site_author: Patrascu Gabriel Vasile
site_description: Meniu pentru lucrul cu baze de date
copyright: Patrascu Gabriel 2015
site_favicon: favicon.ico
theme: readthedocs
pages:
- Acasa: 'index.md'
- Start: 'start.md'
- Start Database: 'start_db.md'
- Stop Database:  'stop_db.md'
- Select: 'select.md'
- Describe: 'describe.md'
- Count: 'count.md'